# Semester Project 2 at ETH
# Hidden Uncertainty for Active Learning
# For further questions contact Claudio Fanconi, fanconic@ethz.ch

name: "baseline_1"
model: "MLP"

data:
    dataset: 'MNIST'
    batch_size: 32

model:
    channel_in: 128
    mlps: [[128, 128, 128],
            [128, 128, 256],
            [256, 256, 512]]
    cls_fc: [256, 256]

optimizer:
    lr: 0.001
    momentum: 0.9
