# Semester Project 2 at ETH
# Hidden Uncertainty for Active Learning
# For further questions contact Claudio Fanconi, fanconic@ethz.ch

name: "resnet_test"

random_state: [3, 11, 42]
save_plot: False
save_df: True
runs: 1
week: 3

training:
    heuristic: "entropy"
    batch_size: 32
    epochs: 20
    ndata_to_label: [100, 200, 200, 200, 200, 1000, 2000, 2000, 2000, 2000, 10000, 10000, 10000, 10000, 0]
    initially_labelled: 100
    initially_balanced: True
    verbose: False
    patience: 5
    lr_reduce_factor: 0.1
    iterations: 5
    early_stopping: False

data:
    dataset: 'cifar10'
    nb_classes: 10
    data_augmentation: False
    img_rows: 32
    img_cols: 32
    img_channels: 3
    val_size: 10000

model:
    ensemble: 1 #set to 1 for no ensemble
    name: "resnet18"
    mir_configs: # only applies if name == MIR
        backbone: "MLP"
        reconstruction_weight: 1.0
        density_model: "gmm"
        warmup: False
        feature_dims: 128
        normalize_features: True
        dim_reduction: 10
    input_height: 32
    input_width: 32
    input_channels: 3
    output_size: 10
    hidden_layers: [128, 128]
    kernel_sizes: [4, 4] # only applied if a (B)CNN is used
    dropout_probabilities: [0.25, 0.5] #[0.25, 0.5]
    use_bias: True
    mc_dropout: False # used for MC dropout
    mc_iterations: 1 # iterations for MC dropout
    kl_div_weight: 0.01 # only used for B(C)NN, to weight the kl_div loss
    adversarial_loss: False
    pretrained: False

optimizer:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
    betas: [0.9, 0.999]