# Semester Project 2 at ETH
# Hidden Uncertainty for Active Learning
# For further questions contact Claudio Fanconi, fanconic@ethz.ch

name: "MLP_ensemble_1"

random_state: 42
save_plot: True

training:
    iterations: 100
    batch_size: 32
    epochs: 100
    ndata_to_label: 10
    initially_labelled: 20
    verbose: False
    patience: 100

data:
    dataset: 'mnist'
    nb_classes: 10
    data_augmentation: False
    img_rows: 28
    img_cols: 28
    img_channels: 1
    val_size: 100

model:
    ensemble: 5 #set to 1 for no ensemble
    name: "MLP"
    input_height: 28
    input_width: 28
    input_channels: 1
    output_size: 10
    hidden_layers: [128, 128]
    kernel_sizes: [3, 3] # only applied if a (B)CNN is used
    dropout_probabilities: [0.0, 0.0] #[0.25, 0.5]
    use_bias: True
    mc_dropout: False # used for MC dropout
    mc_iterations: 1 # iterations for MC dropout
    kl_div_weight: 1 # only used for B(C)NN, to weight the kl_div loss
    adversarial_loss: False

optimizer:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
    betas: [0.9, 0.999]