# Semester Project 2 at ETH
# Hidden Uncertainty for Active Learning
# For further questions contact Claudio Fanconi, fanconic@ethz.ch

name: "test_CNN_3"

random_state: 42
save_plot: True

training:
    batch_size: 32
    epochs: 50
    ndata_to_label: 100
    initially_labelled: 20
    verbose: False
    patience: 10
    lr_reduce_factor: 0.1
    iterations: 10
    early_stopping: False

data:
    dataset: 'mnist'
    nb_classes: 10
    data_augmentation: False
    img_rows: 28
    img_cols: 28
    img_channels: 1
    val_size: 100

model:
    ensemble: 1 #set to 1 for no ensemble
    name: "CNN"
    input_height: 28
    input_width: 28
    input_channels: 1
    output_size: 10
    hidden_layers: [32, 32]
    kernel_sizes: [4, 4] # only applied if a (B)CNN is used
    dropout_probabilities: [0.25, 0.5] #[0.25, 0.5]
    use_bias: True
    mc_dropout: True # used for MC dropout
    mc_iterations: 10 # iterations for MC dropout
    kl_div_weight: 0.01 # only used for B(C)NN, to weight the kl_div loss
    adversarial_loss: False

optimizer:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
    betas: [0.9, 0.999]