# Semester Project 2 at ETH
# Hidden Uncertainty for Active Learning
# For further questions contact Claudio Fanconi, fanconic@ethz.ch

name: "test_cityscapes"

random_state: [3, 11, 42]
save_plot: False
save_df: True
runs: 3
week: 6
problem: "classification" # "segmentation"

training:
    heuristic: "precomputed"
    shuffle_prop: 0.2
    batch_size: 2
    epochs: 60
    ndata_to_label: [100, 200, 200, 200, 200, 1000, 2000, 2000, 2000, 2000, 10000, 10000, 10000, 10000, 0]
    initially_labelled: 100
    initially_balanced: False
    verbose: True
    lr_reduce_factor: 0.1
    patience_lr_reduce: 8
    iterations: 15
    early_stopping: True
    load_best_model: True
    patience_early_stopping: 15

data:
    dataset: 'CityScapes'
    nb_classes: 30
    img_rows: 128
    img_cols: 128
    img_channels: 3
    val_size: 0.2
    augmentation: False
    rgb_normalization: False
    path: "/srv/beegfs02/scratch/density_estimation/data/fanconic/CityScapes" #only applies to CityScapes

model:
    ensemble: 1 #set to 1 for no ensemble
    name: "UNet"
    mir_configs: # only applies if name == MIR
        backbone: "resnet50"
        reconstruction_weight: 1.0
        density_model: "knn"
        warmup: False
        feature_dims: 512
        normalize_features: True
        dim_reduction: -1
        decoder_bn: True
        num_res_blocks: 3

        # Greedy Search
        greedy_search: True
        search_step_size: 100

        # KNN
        knn_weights: "uniform"
        knn_metric: "euclidean"
        knn_neighbours: 5
    
    # Data sizes - need to be the same as in "data"
    input_height: 128
    input_width: 128
    input_channels: 3
    output_size: 1

    # Layers for DNN and CNNS
    hidden_layers: [128, 128]
    kernel_sizes: [4, 4] # only applied if a (B)CNN is used
    dropout_probabilities: [0.05, 0.5] #[0.25, 0.5]
    use_bias: True

    # Monte Carlo Dropout parameters
    mc_dropout: False # used for MC dropout
    mc_iterations: 1 # iterations for MC dropout

    # BNN KL divergence loss
    kl_div_weight: 0.01 # only used for B(C)NN, to weight the kl_div loss

    #Pretrained
    pretrained: False

optimizer:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
    betas: [0.9, 0.999]